# Generated by Django 2.2.5 on 2020-11-12 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('actions_group_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='ActionsGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actions_group',
            },
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('ended', models.TextField()),
                ('ended_time', models.TimeField(blank=True, null=True)),
                ('lesson_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('started_time', models.TimeField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'class_meeting',
            },
        ),
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_note',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('break_duration', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('field', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.BigIntegerField(blank=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('section_count', models.IntegerField(blank=True, null=True)),
                ('section_duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='ConvertedImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'converted_image',
            },
        ),
        migrations.CreateModel(
            name='DayPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('discipline', models.IntegerField(blank=True, null=True)),
                ('discipline_description', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('grade_description', models.CharField(blank=True, max_length=255, null=True)),
                ('presence_state', models.IntegerField(blank=True, null=True)),
                ('student_id', models.BigIntegerField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_point',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('file_link', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_id', models.BigIntegerField(blank=True, null=True)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('student_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'homework',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_unit', models.IntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('field', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('time_in_week', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'menu_item',
            },
        ),
        migrations.CreateModel(
            name='NewExam',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.BigIntegerField()),
                ('class_type', models.CharField(choices=[('O', 'online'), ('I', 'inperson')], max_length=1)),
                ('done', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Classroom')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
            ],
            options={
                'db_table': 'new_exam',
            },
        ),
        migrations.CreateModel(
            name='NewExamMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.NewExam')),
            ],
            options={
                'db_table': 'new_exam_meeting',
            },
        ),
        migrations.CreateModel(
            name='NewHomework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='api.Classroom')),
                ('lesson_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='api.Lesson')),
            ],
            options={
                'db_table': 'new_homework',
            },
        ),
        migrations.CreateModel(
            name='PresenceAbsence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'absent'), ('E', 'entrance'), ('V', 'verified'), ('U', 'end_set_absent')], default='A', max_length=1)),
                ('meeting_score', models.IntegerField(blank=True, null=True)),
                ('has_disciplinary', models.BooleanField(blank=True, default=False)),
                ('disciplinary', models.CharField(blank=True, max_length=100, null=True)),
                ('class_meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sheet', to='api.ClassMeeting')),
            ],
            options={
                'db_table': 'class_sheet',
            },
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('submitted_choices', models.CharField(blank=True, max_length=2000, null=True)),
                ('score_text', models.CharField(blank=True, max_length=200, null=True)),
                ('class_meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClassMeeting')),
            ],
            options={
                'db_table': 'quiz_score',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('duplicate', models.TextField(blank=True, null=True)),
                ('duplicate_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('break_duration', models.IntegerField(blank=True, null=True)),
                ('class_id', models.BigIntegerField(blank=True, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.BigIntegerField(blank=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('section_count', models.IntegerField(blank=True, null=True)),
                ('section_duration', models.IntegerField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('info_completed', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.BigIntegerField(blank=True, null=True)),
                ('class_type', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('section_order', models.IntegerField(blank=True, null=True)),
                ('selected_lesson', models.BigIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='SmsVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.BigIntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sms_verification',
            },
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('class_type', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=255, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('teacher_timeline_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_interval',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timeline',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True)),
                ('cert_code', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('education_state', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('national_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_completed', models.TextField(blank=True, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.BigIntegerField(blank=True, null=True)),
                ('school_id', models.BigIntegerField(blank=True, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.IntegerField(blank=True, null=True)),
                ('birth_certificate_image', models.CharField(blank=True, max_length=255, null=True)),
                ('national_card_image', models.CharField(blank=True, max_length=255, null=True)),
                ('meetings', models.ManyToManyField(blank=True, related_name='students', through='api.PresenceAbsence', to='api.ClassMeeting')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('resource', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'user_resource',
            },
        ),
        migrations.CreateModel(
            name='UserProficiency',
            fields=[
                ('proficiency', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'user_proficiency',
            },
        ),
        migrations.CreateModel(
            name='UserOtherDocumentImages',
            fields=[
                ('other_document_images', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'user_other_document_images',
            },
        ),
        migrations.CreateModel(
            name='UserMyClassesId',
            fields=[
                ('my_classes_id', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'user_my_classes_id',
            },
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'user_images',
            },
        ),
        migrations.CreateModel(
            name='TimeLineReservedTimeIntervals',
            fields=[
                ('reserved_time_intervals', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Timeline')),
            ],
            options={
                'db_table': 'time_line_reserved_time_intervals',
            },
        ),
        migrations.CreateModel(
            name='TimeLineLessons',
            fields=[
                ('lessons', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Timeline')),
            ],
            options={
                'db_table': 'time_line_lessons',
            },
        ),
        migrations.CreateModel(
            name='TimeLineFreeTimeIntervals',
            fields=[
                ('free_time_intervals', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time_line', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Timeline')),
            ],
            options={
                'db_table': 'time_line_free_time_intervals',
            },
        ),
        migrations.CreateModel(
            name='TeacherLessons',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'teacher_lessons',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'SATURDAY'), (2, 'SUNDAY'), (3, 'MONDAY'), (4, 'TUESDAY'), (5, 'WEDNESDAY'), (6, 'THURSDAY'), (7, 'FRIDAY')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('online', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User')),
            ],
            options={
                'db_table': 'teacher_availability',
            },
        ),
        migrations.CreateModel(
            name='SectionLessons',
            fields=[
                ('lessons', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Section')),
            ],
            options={
                'db_table': 'section_lessons',
            },
        ),
        migrations.CreateModel(
            name='SchoolLevels',
            fields=[
                ('levels', models.IntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.School')),
            ],
            options={
                'db_table': 'school_levels',
            },
        ),
        migrations.CreateModel(
            name='SchoolDegrees',
            fields=[
                ('degrees', models.IntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.School')),
            ],
            options={
                'db_table': 'school_degrees',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSections',
            fields=[
                ('sections', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Schedule')),
            ],
            options={
                'db_table': 'schedule_sections',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('menu', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Role')),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
        migrations.CreateModel(
            name='RoleAcctionsGroup',
            fields=[
                ('acctions_group', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Role')),
            ],
            options={
                'db_table': 'role_acctions_group',
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(blank=True, max_length=200, null=True)),
                ('quiz_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('quiz_type', models.CharField(choices=[('Q', 'quiz'), ('E', 'exam')], max_length=1)),
                ('students', models.ManyToManyField(blank=True, related_name='quizzes', through='api.QuizScore', to='api.User')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_quiz', to='api.User')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Quizzes'),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
        migrations.AddField(
            model_name='presenceabsence',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sheet', to='api.User'),
        ),
        migrations.CreateModel(
            name='NewHomeworkResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('submitdate', models.DateTimeField(blank=True, default=None, null=True)),
                ('homework_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_response', to='api.NewHomework')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks_response', to='api.User')),
            ],
            options={
                'db_table': 'new_homework_response',
            },
        ),
        migrations.AddField(
            model_name='newhomework',
            name='responses',
            field=models.ManyToManyField(blank=True, related_name='homeworks', through='api.NewHomeworkResponse', to='api.User'),
        ),
        migrations.CreateModel(
            name='NewExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('submitted_choices', models.CharField(blank=True, max_length=2000, null=True)),
                ('score_text', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.NewExamMeeting')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Quizzes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'new_exam_score',
            },
        ),
        migrations.AddField(
            model_name='newexammeeting',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='exam_meeting', through='api.NewExamScore', to='api.User'),
        ),
        migrations.CreateModel(
            name='MeetingScorePerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Classroom')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_scores', to='api.User')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_scores', to='api.User')),
            ],
            options={
                'db_table': 'meeting_score_per_day',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.TextField(blank=True, null=True)),
                ('modified_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.IntegerField(blank=True, null=True)),
                ('exam_date', models.DateTimeField(blank=True, null=True)),
                ('exam_duration', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_id', models.BigIntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('has_disciplinary', models.BooleanField(blank=True, default=False)),
                ('disciplinary', models.CharField(blank=True, max_length=100, null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Classroom')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Lesson')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_notes', to='api.User')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_notes', to='api.User')),
            ],
            options={
                'db_table': 'disciplinary_per_day',
            },
        ),
        migrations.CreateModel(
            name='ClassroomStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_students', to='api.Classroom')),
                ('students', models.ForeignKey(blank=True, db_column='students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_students', to='api.User')),
            ],
            options={
                'db_table': 'classroom_students',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', through='api.ClassroomStudents', to='api.User'),
        ),
        migrations.CreateModel(
            name='ClassMeetingStudents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('class_meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ClassMeeting')),
                ('students', models.ForeignKey(db_column='students', on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
            options={
                'db_table': 'class_meeting_students',
            },
        ),
        migrations.AddField(
            model_name='classmeeting',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Classroom'),
        ),
        migrations.AddField(
            model_name='classmeeting',
            name='section_id',
            field=models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Section'),
        ),
        migrations.CreateModel(
            name='ActionsGroupActions',
            fields=[
                ('actions', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actions_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.ActionsGroup')),
            ],
            options={
                'db_table': 'actions_group_actions',
            },
        ),
    ]
