# Generated by Django 2.2.5 on 2020-11-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newexammeeting_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
