# Generated by Django 2.2.5 on 2020-11-21 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initail_data'),
        ('api', '0004_auto_20201119_0919'),
    ]

    operations = [
    ]
