# Generated by Django 3.1.3 on 2021-01-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_update_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('max_disk_usage', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'disk_usage',
            },
        ),
        migrations.CreateModel(
            name='SavedVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('disk_usage', models.IntegerField(blank=True, null=True)),
                ('class_meeting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='videos', to='api.classmeeting')),
            ],
            options={
                'db_table': 'saved_videos',
            },
        ),
    ]
